name: GraphQL Schema Update

on:
  push:
  workflow_dispatch:
    inputs:
      app_env:
        type: choice
        description: Environment you want to check against
        required: false
        default: stage
        options:
          - stage
          - dev
          - prod

jobs:
  update-graphql-schema:
    name: Update GraphQL Schema
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: "14.17"

      # - run: type > schema.graphql
      # - run: type > test.txt

      # - run: type > src/store/apollo/schema.graphql

      - run: echo "hello world" > src/store/apollo/possibleTypes/introspectionResults.ts

      # - run: echo "hello world" > src/store/apollo/possibleTypes/should-not-commit.ts

      - run: echo "hello world" > src/store/api/graph/interfaces/types.ts

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/github-script@v6
        env:
          REACT_APP_SERVICES_ENV: ${{ github.event.inputs.app_env }}
        with:
          script: |
            console.log(process.env);
            console.log("i'm being triggered!")

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create/Update Pull Request for GraphQL SDL
        uses: lucaslim/ed3-web/.github/actions/create-schema-pull-request@lucaslim-patch-16
        with:
          path: "src/store/apollo/schema.graphql"
          commit-message: "[hotfix] update schema definition language ðŸ©»"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create/Update Pull Request for Possible Types
        uses: lucaslim/ed3-web/.github/actions/create-schema-pull-request@lucaslim-patch-16
        with:
          path: "src/store/apollo/possibleTypes/introspectionResults.ts"
          commit-message: "[hotfix] update possible types ðŸ”®"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create/Update Pull Request for GraphQL Schema & Operation types
        uses: lucaslim/ed3-web/.github/actions/create-schema-pull-request@lucaslim-patch-16
        with:
          path: "src/store/api/graph/interfaces/types.ts"
          commit-message: "[hotfix] update graphql schema/operation types â›“"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
