on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      # must keep this extra checkout step until this bug is fixed: https://github.com/actions/checkout/issues/692
      - name: Checkout repository
        uses: actions/checkout@v3
        if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'ready_for_review'
        
      - name: Check PR Limit
        uses: lucaslim/pull-request-limiter-action@main
        if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'ready_for_review'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          limit: 3
          auto_close: false
          body: |
            Hola @${{ github.actor }}
          
            You currently have too many opened Pull Requests. Please close this and reopen it once you have less than 3.

            **For more information, please refer to our [Pull Request Checklist](https://einc.atlassian.net/l/cp/d84EDpzo).**

            **Or you could also...**
            - Ask a repository administrators to bypass this check.
            - See if any of your open Pull Requests can be improved.
            - Ask reviewers to review your opened Pull Requests.
            - Review Pull Requests from other developers.
            - Improve our documentation.
            
  circle:
    runs-on: ubuntu-latest
    steps:
      - name: Run Cypress Tests
        id: cypress-test
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://circleci.com/api/v2/project/gh/carmigo/edealer-web-v2/pipeline'
          method: 'POST'
          customHeaders: >-
            {
              "x-attribution-login": "lucaslim",
              "x-attribution-actor-id": "lucaslim",
              "Circle-Token": "${{ secrets.CIRCLECI_TOKEN }}"
            }
          data: >-
            {
              "branch": "fix-dashboard-magic",
              "parameters": {
                "appEnv": "dev",
                "baseUrl": "https://6326650f9eada32fdb0d864d--edealer-web-dev.netlify.app",
                "event": "push",
                "reason": "",
                "runLocal": false
              }
            }
      - name: Show Response
        run: |
          echo ${{ steps.cypress-test.outputs.response }}
          echo ${{ steps.cypress-test.outputs.headers }}
          echo ${{ fromJson(steps.cypress-test.outputs.response) }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}.
  print-thingz:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/github-script@v6
      env:
        HELLO: WORLD
      with:
        script: |
          console.log(process.env);
          console.log("i'm being triggered!")
    - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Check out repository code
      uses: actions/checkout@v2
    - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
    - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - run: echo "ğŸ This job's status is ${{ job.status }}.
